export const ACTIVITY_EVENT_KIND = {
  CHECK_IN_CREATED: "CHECK_IN_CREATED",
  COMMUNITY_ALERT_VIEWED: "COMMUNITY_ALERT_VIEWED",
  RESOURCE_OPENED: "RESOURCE_OPENED",
} as const;

export type ActivityEventKind =
  (typeof ACTIVITY_EVENT_KIND)[keyof typeof ACTIVITY_EVENT_KIND];
