import { jsPDF } from "jspdf";
import { formatSosDateTime } from "@/lib/datetime/format-datetime";
import type { IncidentReportData } from "@/lib/services/incident-report.service";
import { formatResponseSummary } from "@/lib/services/incident-report.service";

export function generateIncidentReportPdf(
  report: IncidentReportData,
  timeZone?: string | null,
): Uint8Array {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 48;
  let y = margin;

  const addLine = (text: string, size = 11, bold = false) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    const lines = doc.splitTextToSize(text, 515);
    for (const line of lines) {
      if (y > 760) {
        doc.addPage();
        y = margin;
      }
      doc.text(line, margin, y);
      y += size + 6;
    }
  };

  addLine("Life Guardian — Emergency Incident Report", 16, true);
  y += 4;
  addLine(`Incident ID: ${report.alertId}`);
  addLine(`Timestamp: ${formatSosDateTime(report.timestamp, timeZone)} (${timeZone ?? "UTC"})`);
  addLine(`Status: ${report.incidentStatus}`);
  addLine(`Escalation: ${report.escalationStatus}`);
  y += 8;
  addLine("Location", 12, true);
  addLine(report.locationLabel);
  if (report.mapsUrl) {
    addLine(`Maps: ${report.mapsUrl}`);
  }
  y += 8;
  addLine("Alert Message", 12, true);
  addLine(report.message?.trim() || "No message provided.");
  y += 8;
  addLine("Contacts Notified", 12, true);
  addLine(String(report.contactsNotified));
  addLine(`Response summary: ${formatResponseSummary(report.responses)}`);
  y += 8;
  addLine("Contact Responses", 12, true);
  if (report.responses.length === 0) {
    addLine("No contact response records.");
  } else {
    for (const response of report.responses) {
      const responded = response.respondedAt
        ? formatSosDateTime(response.respondedAt, timeZone)
        : "Not yet";
      addLine(`• ${response.contactName}: ${response.status} (${responded})`);
    }
  }
  y += 12;
  addLine("Generated by Life Guardian Emergency Response Platform.", 9);

  return new Uint8Array(doc.output("arraybuffer"));
}
